FROM ghcr.io/actions/actions-runner:latest

RUN sudo apt update -y && \
    sudo apt install -y \
    curl \
    bzip2 \
    curl \
    g++ \
    gcc \
    make \
    jq \
    tar \
    unzip \
    wget
