name: Build & Publish Docker Images
# Build & Push rebuilds the tendermint docker image on every push to main and creation of tags
# and pushes the image to GHCR
on:
  workflow_dispatch: # Allow manual trigger
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    strategy:
      matrix:
        app: [ubuntu]
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: chronicleprotocol/actions-workflows/.github/workflows/docker-build-and-publish.yaml@main
    with:
      application: actions-runner-${{ matrix.app }}
      context: ${{ matrix.app }}
      dockerfile: ${{ matrix.app }}/Dockerfile
      tag_latest: true
      tag_ref: true
