name: Build & Publish Docker Images
# Build & Push rebuilds the tendermint docker image on every push to master and creation of tags
# and pushes the image to GHCR
on:
  workflow_dispatch: # Allow manual trigger
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build-and-push:
    runs-on: arc-runner-set
    strategy:
      matrix:
        app: [ubuntu]
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (tags, labels, etc)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chronicleprotocol/actions-runner-${{ matrix.app }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Docker build and Push images
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.app }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

